const CACHE = 'second-look-4-u-v21';

async function appResponse(request) {
  const response = await fetch(request);
  if (!response.ok) return response;
  const type = response.headers.get('content-type') || '';
  if (!type.includes('text/html')) return response;
  let html = await response.text();
  html = html.replace('</style>', `textarea.note{display:block !important;min-height:72px;resize:vertical;} .note-row{align-items:flex-start;} .voice{min-width:52px;} body:has(.launch) .top{display:none;} body:has(.launch) .wrap{padding-bottom:0;} body:has(.launch) .launch{min-height:100vh;align-items:flex-start;padding-top:clamp(72px,12vh,120px);padding-bottom:48px;} body:has(.launch) .app-mark{margin-bottom:20px;} body:has(.launch) .launch-title{font-size:clamp(34px,9vw,43px);margin-bottom:14px;} body:has(.launch) .launch-sub{margin-bottom:24px;} .do-not-start-title{font-size:clamp(34px,9vw,43px);line-height:1.05;letter-spacing:-.035em;margin:18px 0 20px;color:var(--txt)} .vehicle-prompt{color:var(--muted);font-size:15px;text-transform:uppercase;letter-spacing:.08em;font-weight:800;margin:2px 0 10px} .note-help{color:var(--muted);font-size:12px;line-height:1.35;margin:0 0 7px}.completion-banner{background:#15191e;border:1px solid var(--gold);border-radius:14px;padding:14px 16px;margin-bottom:16px}.completion-banner strong{display:block;color:var(--gold);font-size:13px;letter-spacing:.08em;margin-bottom:4px}.completion-banner span{color:var(--muted);font-size:13px;line-height:1.4}.cold-warning{margin-top:12px;padding:12px;border-radius:11px;background:#2a1b18;border:1px solid var(--red);color:var(--txt);font-size:13px;line-height:1.45}.cold-warning strong{display:block;margin-bottom:4px;color:var(--red)}#next:disabled{opacity:.45;cursor:not-allowed}</style>`);
  const voiceFix = `<script>function setupVoiceNotes(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;document.querySelectorAll('[data-voice]').forEach(btn=>btn.onclick=()=>{const id=btn.dataset.voice,note=document.querySelector('[data-note="'+id+'"]'),status=document.querySelector('[data-voice-status="'+id+'"]');note.classList.add('show');note.focus();if(!SR){status.textContent='Voice input is not available here. Use the microphone on the iPhone keyboard.';return;}let r=results.find(z=>z.id===id);if(!r){r={id};results.push(r)}const rec=new SR();rec.lang='en-GB';rec.interimResults=true;rec.continuous=false;let finished=false;const finish=()=>{if(finished)return;finished=true;btn.classList.remove('listening')};btn.classList.add('listening');status.textContent='Listening… speak now';rec.onresult=e=>{let text='';for(let i=e.resultIndex;i<e.results.length;i++)text+=e.results[i][0].transcript;note.value=text.trim();r.note=note.value;status.textContent='Voice note added.'};rec.onerror=()=>{status.textContent='Voice input could not be used. Try the keyboard microphone.';finish()};rec.onend=()=>finish();try{rec.start()}catch(e){finish();status.textContent='Voice input could not be started. Try the keyboard microphone.'}})}</script>`;
  const sectionGate = `<script>(function(){function gate(){try{const frame=document.querySelector('iframe');const w=frame&&frame.contentWindow;const d=frame&&frame.contentDocument;if(!w||!d||!Array.isArray(w.S)||typeof w.section!=='number'||!w.answers)return;const next=d.getElementById('next');if(!next)return;const current=w.S[w.section];if(!current||!Array.isArray(current.items))return;const incomplete=current.items.filter(function(item){const id=item&&item[0];return id&&!(w.answers[id]&&w.answers[id].status)});const complete=incomplete.length===0;next.disabled=!complete;next.setAttribute('aria-disabled',complete?'false':'true');next.title=complete?'':'Complete every item in this section before continuing.';if(!next.dataset.slSectionGate){next.dataset.slSectionGate='1';next.addEventListener('click',function(e){const now=w.S[w.section];const missing=now&&now.items?now.items.filter(function(item){const id=item&&item[0];return id&&!(w.answers[id]&&w.answers[id].status)}):[];if(missing.length){e.preventDefault();e.stopImmediatePropagation();next.disabled=true;return false}},true)}}catch(e){}}setInterval(gate,150);window.addEventListener('load',gate)})();</script>`;
  const inject = voiceFix + sectionGate + '<script src="./ux.js?v=19"></script><script src="./vehicle-fix.js?v=20"></script>';
  if (html.includes('</body>')) html = html.replace('</body>', inject + '</body>'); else html += inject;
  return new Response(html,{status:response.status,statusText:response.statusText,headers:response.headers});
}

self.addEventListener('install',event=>{event.waitUntil((async()=>{const cache=await caches.open(CACHE);try{const response=await appResponse(new Request('./index.html',{cache:'no-store'}));await cache.put('./index.html',response.clone());}catch(e){}try{await cache.add('./manifest.webmanifest');}catch(e){} })());self.skipWaiting();});

self.addEventListener('activate',event=>event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));

self.addEventListener('fetch',event=>{if(event.request.method!=='GET')return;const url=new URL(event.request.url);if(url.pathname.endsWith('/index.html')||url.pathname.endsWith('/second-look-4-u/')){event.respondWith((async()=>{try{return await appResponse(new Request(event.request.url,{method:'GET',headers:event.request.headers,cache:'no-store'}));}catch(e){return caches.match('./index.html');}})());}else{event.respondWith(caches.match(event.request).then(cached=>cached||fetch(event.request)));}});
