const CACHE = 'second-look-4-u-v26';

async function appResponse(request) {
  const response = await fetch(request);
  if (!response.ok) return response;
  const type = response.headers.get('content-type') || '';
  if (!type.includes('text/html')) return response;
  let html = await response.text();
  const voiceFix = `<script>function setupVoiceNotes(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;document.querySelectorAll('[data-voice]').forEach(btn=>btn.onclick=()=>{const id=btn.dataset.voice,note=document.querySelector('[data-note="'+id+'"]'),status=document.querySelector('[data-voice-status="'+id+'"]');note.classList.add('show');note.focus();if(!SR){status.textContent='Voice input is not available here. Use the microphone on the iPhone keyboard.';return;}let r=results.find(z=>z.id===id);if(!r){r={id};results.push(r)}const rec=new SR();rec.lang='en-GB';rec.interimResults=true;rec.continuous=false;rec.onresult=e=>{let text='';for(let i=e.resultIndex;i<e.results.length;i++)text+=e.results[i][0].transcript;note.value=text.trim();r.note=note.value;status.textContent='Voice note added.'};rec.onerror=()=>{status.textContent='Voice input could not be used. Try the keyboard microphone.'};rec.onend=()=>btn.classList.remove('listening');btn.classList.add('listening');status.textContent='Listening… speak now';try{rec.start()}catch(e){status.textContent='Voice input could not be started. Try the keyboard microphone.'}})}</script>`;
  const sectionGate = `<script>(function(){function gate(){try{const frame=document.querySelector('iframe'),w=frame&&frame.contentWindow,d=frame&&frame.contentDocument;if(!w||!d||!Array.isArray(w.S)||typeof w.section!=='number'||!w.answers)return;const next=d.getElementById('next');if(!next)return;const current=w.S[w.section];if(!current||!Array.isArray(current.items))return;const incomplete=current.items.filter(item=>item&&item[0]&&!(w.answers[item[0]]&&w.answers[item[0]].status));next.disabled=incomplete.length>0;next.title=incomplete.length?'Complete every item in this section before continuing.':'';}catch(e){}}setInterval(gate,150)})();</script>`;
  const inject = voiceFix + sectionGate + '<script src="./ux.js?v=20"></script><script src="./vehicle-fix.js?v=24"></script><script src="./live-fixes.js?v=3"></script>';
  if(html.includes('</body>'))html=html.replace('</body>',inject+'</body>');else html+=inject;
  return new Response(html,{status:response.status,statusText:response.statusText,headers:response.headers});
}
self.addEventListener('install',event=>{event.waitUntil((async()=>{const cache=await caches.open(CACHE);try{const response=await appResponse(new Request('./index.html',{cache:'no-store'}));await cache.put('./index.html',response.clone());}catch(e){}try{await cache.add('./manifest.webmanifest')}catch(e){}})());self.skipWaiting()});
self.addEventListener('activate',event=>event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
self.addEventListener('fetch',event=>{if(event.request.method!=='GET')return;const url=new URL(event.request.url);if(url.pathname.endsWith('/index.html')||url.pathname.endsWith('/second-look-4-u/'))event.respondWith((async()=>{try{return await appResponse(new Request(event.request.url,{method:'GET',headers:event.request.headers,cache:'no-store'}))}catch(e){return caches.match('./index.html')}})());else event.respondWith(caches.match(event.request).then(cached=>cached||fetch(event.request)))});
