const CACHE = 'second-look-4-u-v17';

async function appResponse(request) {
  const response = await fetch(request);
  if (!response.ok) return response;
  const type = response.headers.get('content-type') || '';
  if (!type.includes('text/html')) return response;
  let html = await response.text();
  html = html.replace('</style>', 'body:has(.launch) .top{display:none;} body:has(.launch) .wrap{padding-bottom:0;} body:has(.launch) .launch{min-height:100vh;align-items:flex-start;padding-top:clamp(72px,12vh,120px);padding-bottom:48px;} textarea.note{display:block !important;min-height:72px;resize:vertical;} .note-row{align-items:flex-start;} .voice{min-width:52px;} .completion-banner{background:#15191e;border:1px solid var(--gold);border-radius:14px;padding:14px 16px;margin-bottom:16px}.completion-banner strong{display:block;color:var(--gold);font-size:13px;letter-spacing:.08em;margin-bottom:4px}.completion-banner span{color:var(--muted);font-size:13px;line-height:1.4}</style>');
  const launchFix = `<script>(function(){function install(){if(window.__slLaunchFixed)return;const b=document.querySelector('.launch .btn');if(!b||typeof vehicleTypes==='undefined'||typeof buildPreflight!=='function')return;window.__slLaunchFixed=true;b.onclick=function(e){e.preventDefault();e.stopImmediatePropagation();const s=document.createElement('select');Object.entries(vehicleTypes).forEach(([k,v])=>{const o=document.createElement('option');o.value=k;o.textContent=v.name;s.appendChild(o)});buildPreflight(s)}}const m=new MutationObserver(install);m.observe(document.body,{childList:true,subtree:true});setTimeout(install,50)})();</script>`;
  const voiceFix = `<script>function setupVoiceNotes(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;document.querySelectorAll('[data-voice]').forEach(btn=>btn.onclick=()=>{const id=btn.dataset.voice,note=document.querySelector('[data-note="'+id+'"]'),status=document.querySelector('[data-voice-status="'+id+'"]');note.classList.add('show');note.focus();if(!SR){status.textContent='Voice input is not available here. Use the microphone on the iPhone keyboard.';return}let r=results.find(z=>z.id===id);if(!r){r={id};results.push(r)}const base=note.value.trim(),rec=new SR();rec.lang='en-GB';rec.interimResults=true;rec.continuous=false;let finished=false;const finish=()=>{if(finished)return;finished=true;btn.classList.remove('listening')};btn.classList.add('listening');status.textContent='Listening… speak now';rec.onresult=e=>{let f='',i='';for(let n=e.resultIndex;n<e.results.length;n++){const t=e.results[n][0].transcript;e.results[n].isFinal?f+=t:i+=t}note.value=((base?base+' ':'')+(f||i)).trim();r.note=note.value;status.textContent=f?'Voice note added.':'Listening…'};rec.onerror=e=>{status.textContent=e.error==='not-allowed'?'Microphone access was blocked. Check Safari microphone permission.':'Voice input could not be used. Try again or use the keyboard microphone.';finish()};rec.onend=()=>{finish();if(status.textContent==='Listening…'||status.textContent==='Listening… speak now')status.textContent='Voice input ended.'};try{rec.start()}catch(e){finish();status.textContent='Voice input could not be started. Try again or use the keyboard microphone.'}})}</script>`;
  const inject=launchFix+voiceFix+'<script src="./ux.js"></script>';
  if(html.includes('</body>'))html=html.replace('</body>',inject+'</body>');else html+=inject;
  return new Response(html,{status:response.status,statusText:response.statusText,headers:response.headers});
}
self.addEventListener('install',event=>{event.waitUntil((async()=>{const cache=await caches.open(CACHE);const response=await appResponse(new Request('./index.html'));await cache.put('./index.html',response.clone());await cache.add('./manifest.webmanifest');await cache.add('./');try{await cache.add('./ux.js')}catch(e){}})());self.skipWaiting()});
self.addEventListener('activate',event=>event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
self.addEventListener('fetch',event=>{if(event.request.method!=='GET')return;const url=new URL(event.request.url);if(url.pathname.endsWith('/index.html')||url.pathname.endsWith('/second-look-4-u/'))event.respondWith(caches.match('./index.html').then(cached=>cached||appResponse(event.request)));else event.respondWith(caches.match(event.request).then(cached=>cached||fetch(event.request)))})
